### PR TITLE
embeddings: Fix issue caused by new implementation of BatchTexts function

### LINKED ISSUE #455: bug: "number of vectors from embedder does not match number of documents"
when add #454, just found:
```bash
abirdcfly@ecs-4fc018ff-1ded-4c65-92dc-67dc1911226c:~/go/src/langchaingo/vectorstores/weaviate$ git show --format="%h" --no-patch
351b8b5
abirdcfly@ecs-4fc018ff-1ded-4c65-92dc-67dc1911226c:~/go/src/langchaingo/vectorstores/weaviate$ go test -v ./...
=== RUN   TestWeaviateStoreRest
=== PAUSE TestWeaviateStoreRest
=== RUN   TestWeaviateStoreRestWithScoreThreshold
=== PAUSE TestWeaviateStoreRestWithScoreThreshold
=== RUN   TestSimilaritySearchWithInvalidScoreThreshold
=== PAUSE TestSimilaritySearchWithInvalidScoreThreshold
=== RUN   TestWeaviateAsRetriever
=== PAUSE TestWeaviateAsRetriever
=== RUN   TestWeaviateAsRetrieverWithScoreThreshold
=== PAUSE TestWeaviateAsRetrieverWithScoreThreshold
=== RUN   TestWeaviateAsRetrieverWithMetadataFilterEqualsClause
=== PAUSE TestWeaviateAsRetrieverWithMetadataFilterEqualsClause
=== RUN   TestWeaviateAsRetrieverWithMetadataFilterNotSelected
=== PAUSE TestWeaviateAsRetrieverWithMetadataFilterNotSelected
=== RUN   TestWeaviateAsRetrieverWithMetadataFilters
=== PAUSE TestWeaviateAsRetrieverWithMetadataFilters
=== CONT  TestWeaviateStoreRest
=== CONT  TestWeaviateAsRetrieverWithScoreThreshold
=== CONT  TestWeaviateAsRetrieverWithMetadataFilterNotSelected
=== CONT  TestWeaviateAsRetrieverWithMetadataFilters
=== CONT  TestWeaviateAsRetrieverWithMetadataFilterEqualsClause
=== CONT  TestSimilaritySearchWithInvalidScoreThreshold
=== CONT  TestWeaviateAsRetriever
=== CONT  TestWeaviateStoreRestWithScoreThreshold
=== NAME  TestWeaviateStoreRest
    weaviate_test.go:94:
                Error Trace:    /home/abirdcfly/go/src/langchaingo/vectorstores/weaviate/weaviate_test.go:94
                Error:          Received unexpected error:
                                number of vectors from embedder does not match number of documents
                Test:           TestWeaviateStoreRest
--- FAIL: TestWeaviateStoreRest (7.02s)
=== NAME  TestWeaviateAsRetriever
    weaviate_test.go:233:
                Error Trace:    /home/abirdcfly/go/src/langchaingo/vectorstores/weaviate/weaviate_test.go:233
                Error:          Received unexpected error:
                                number of vectors from embedder does not match number of documents
                Test:           TestWeaviateAsRetriever
--- FAIL: TestWeaviateAsRetriever (7.59s)
=== NAME  TestWeaviateAsRetrieverWithMetadataFilterNotSelected
    weaviate_test.go:448:
                Error Trace:    /home/abirdcfly/go/src/langchaingo/vectorstores/weaviate/weaviate_test.go:448
                Error:          Received unexpected error:
                                number of vectors from embedder does not match number of documents
                Test:           TestWeaviateAsRetrieverWithMetadataFilterNotSelected
--- FAIL: TestWeaviateAsRetrieverWithMetadataFilterNotSelected (7.59s)
=== NAME  TestWeaviateAsRetrieverWithMetadataFilters
    weaviate_test.go:519:
                Error Trace:    /home/abirdcfly/go/src/langchaingo/vectorstores/weaviate/weaviate_test.go:519
                Error:          Received unexpected error:
                                number of vectors from embedder does not match number of documents
                Test:           TestWeaviateAsRetrieverWithMetadataFilters
--- FAIL: TestWeaviateAsRetrieverWithMetadataFilters (7.74s)
=== NAME  TestWeaviateAsRetrieverWithMetadataFilterEqualsClause
    weaviate_test.go:360:
                Error Trace:    /home/abirdcfly/go/src/langchaingo/vectorstores/weaviate/weaviate_test.go:360
                Error:          Received unexpected error:
                                number of vectors from embedder does not match number of documents
                Test:           TestWeaviateAsRetrieverWithMetadataFilterEqualsClause
--- FAIL: TestWeaviateAsRetrieverWithMetadataFilterEqualsClause (7.93s)
=== NAME  TestWeaviateAsRetrieverWithScoreThreshold
    weaviate_test.go:281:
                Error Trace:    /home/abirdcfly/go/src/langchaingo/vectorstores/weaviate/weaviate_test.go:281
                Error:          Received unexpected error:
                                number of vectors from embedder does not match number of documents
                Test:           TestWeaviateAsRetrieverWithScoreThreshold
--- FAIL: TestWeaviateAsRetrieverWithScoreThreshold (7.93s)
=== NAME  TestSimilaritySearchWithInvalidScoreThreshold
    weaviate_test.go:187:
                Error Trace:    /home/abirdcfly/go/src/langchaingo/vectorstores/weaviate/weaviate_test.go:187
                Error:          Received unexpected error:
                                number of vectors from embedder does not match number of documents
                Test:           TestSimilaritySearchWithInvalidScoreThreshold
--- FAIL: TestSimilaritySearchWithInvalidScoreThreshold (7.95s)
=== NAME  TestWeaviateStoreRestWithScoreThreshold
    weaviate_test.go:137:
                Error Trace:    /home/abirdcfly/go/src/langchaingo/vectorstores/weaviate/weaviate_test.go:137
                Error:          Received unexpected error:
                                number of vectors from embedder does not match number of documents
                Test:           TestWeaviateStoreRestWithScoreThreshold
--- FAIL: TestWeaviateStoreRestWithScoreThreshold (7.95s)
FAIL
FAIL    github.com/tmc/langchaingo/vectorstores/weaviate        7.956s
FAIL
```
But after rollback the last commit, the test basically passed.（ IMO, `AsRetrieverWithScoreThreshold` always has a probability of not passing, because openai returns are not fixed...)
```
abirdcfly@ecs-4fc018ff-1ded-4c65-92dc-67dc1911226c:~/go/src/langchaingo/vectorstores/weaviate$ git reset --hard HEAD^
HEAD is now at 213b9dc examples: Update langchaingo to v0.1.1 (#445)
abirdcfly@ecs-4fc018ff-1ded-4c65-92dc-67dc1911226c:~/go/src/langchaingo/vectorstores/weaviate$ git show --format="%h" --no-patch
213b9dc
abirdcfly@ecs-4fc018ff-1ded-4c65-92dc-67dc1911226c:~/go/src/langchaingo/vectorstores/weaviate$ go test -v ./...
=== RUN   TestWeaviateStoreRest
=== PAUSE TestWeaviateStoreRest
=== RUN   TestWeaviateStoreRestWithScoreThreshold
=== PAUSE TestWeaviateStoreRestWithScoreThreshold
=== RUN   TestSimilaritySearchWithInvalidScoreThreshold
=== PAUSE TestSimilaritySearchWithInvalidScoreThreshold
=== RUN   TestWeaviateAsRetriever
=== PAUSE TestWeaviateAsRetriever
=== RUN   TestWeaviateAsRetrieverWithScoreThreshold
=== PAUSE TestWeaviateAsRetrieverWithScoreThreshold
=== RUN   TestWeaviateAsRetrieverWithMetadataFilterEqualsClause
=== PAUSE TestWeaviateAsRetrieverWithMetadataFilterEqualsClause
=== RUN   TestWeaviateAsRetrieverWithMetadataFilterNotSelected
=== PAUSE TestWeaviateAsRetrieverWithMetadataFilterNotSelected
=== RUN   TestWeaviateAsRetrieverWithMetadataFilters
=== PAUSE TestWeaviateAsRetrieverWithMetadataFilters
=== CONT  TestWeaviateStoreRest
=== CONT  TestWeaviateAsRetrieverWithScoreThreshold
=== CONT  TestSimilaritySearchWithInvalidScoreThreshold
=== CONT  TestWeaviateAsRetrieverWithMetadataFilterNotSelected
=== CONT  TestWeaviateAsRetrieverWithMetadataFilters
=== CONT  TestWeaviateAsRetrieverWithMetadataFilterEqualsClause
=== CONT  TestWeaviateAsRetriever
=== CONT  TestWeaviateStoreRestWithScoreThreshold
--- PASS: TestWeaviateStoreRest (6.11s)
--- PASS: TestWeaviateAsRetrieverWithMetadataFilters (7.88s)
--- PASS: TestWeaviateAsRetriever (7.95s)
--- PASS: TestWeaviateAsRetrieverWithMetadataFilterEqualsClause (8.43s)
--- PASS: TestSimilaritySearchWithInvalidScoreThreshold (8.75s)
--- PASS: TestWeaviateAsRetrieverWithMetadataFilterNotSelected (9.51s)
--- PASS: TestWeaviateStoreRestWithScoreThreshold (9.60s)
=== NAME  TestWeaviateAsRetrieverWithScoreThreshold
    weaviate_test.go:294:
                Error Trace:    /home/abirdcfly/go/src/langchaingo/vectorstores/weaviate/weaviate_test.go:294
                Error:          "The chair beside the desk is beige, and the lamp beside the desk is black." does not contain "orange"
                Test:           TestWeaviateAsRetrieverWithScoreThreshold
                Messages:       expected orange in result
--- FAIL: TestWeaviateAsRetrieverWithScoreThreshold (9.86s)
FAIL
FAIL    github.com/tmc/langchaingo/vectorstores/weaviate        9.872s
FAIL
```
I think other vectorstores will be facing the same situation.

### PR DESCRIPTION
**Pull request by jaylalakiya**
Fixes #455 

This issue was an aftereffect of PR (#453 ) by me where I fixed the BatchTexts function but the places where BatchTexts function is used were not changed according to new implementation.

So this PR fixes the places where that function was used.

This is inspired by js library implementation https://github.com/langchain-ai/langchainjs/blob/4e9e23137de8d2bc61dfbcf05e8e35a8f1e89ef5/langchain/src/embeddings/openai.ts#L159 

I'll change this later on to process batches concurrently but for now this will fix issues.

### PR Checklist

- [x] Read the [Contributing documentation](https://github.com/tmc/langchaingo/blob/main/CONTRIBUTING.md).
- [x] Read the [Code of conduct documentation](https://github.com/tmc/langchaingo/blob/main/CODE_OF_CONDUCT.md).
- [x] Name your Pull Request title clearly, concisely, and prefixed with the name of the primarily affected package you changed according to [Good commit messages](https://go.dev/doc/contribute#commit_messages) (such as `memory: add interfaces for X, Y` or `util: add whizzbang helpers`).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `Fixes #123`).
- [x] Describes the source of new concepts.
- [x] References existing implementations as appropriate.
- [x] Contains test coverage for new functions.
- [x] Passes all [`golangci-lint`](https://golangci-lint.run/) checks.

### CODE REVIEW

**Review by tmc — APPROVED** [review]
LGTM

File: embeddings/embedding.go [hunk 1]
```diff
@@ -91,28 +91,12 @@ func BatchedEmbed(ctx context.Context, embedder EmbedderClient, texts []string,
...
-			emb = append(emb, curTextEmbeddings[0])
-			continue
-		}
-
-		textLengths := make([]int, 0, len(texts))
-		for _, text := range texts {
-			textLengths = append(textLengths, len(text))
-		}
-
-		combined, err := CombineVectors(curTextEmbeddings, textLengths)
```
Comment (eliben) [inline embeddings/embedding.go:110]: This commit entirely removes the `CombineVectors` functionality that was here before.

In fact, `CombineVectors` now becomes unused; why is this?

Comment (eliben) [reply embeddings/embedding.go:110]: @tmc FYI

Comment (jaylalakiya) [reply embeddings/embedding.go:110]: Hi @eliben
Sorry for delay in response. I have removed CombineVectors as it is not needed in newer implementation. Previously, batchTexts function was splitting text into parts, then we request for embeddings and combine them to get embeddings for required text. Newer implementation of batchTexts which is inspired from js library doesnt split the text instead it batches the texts and hence we dont need to use CombineVectors.

Assume batchSize = 2 for following example

Previous implementation:
if input to batchTexts = ["str1", "str2", "str3"] it outputs [["st", "r1"], ["st", "r2"], ["st", "r3"]] and then we request for embeddings and we used CombineVectors on embeddings for ["st", "r1"] to get embeddings for "str1"

Newer implementation:
if input to batchTexts = ["str1", "str2", "str3"] it outputs [["str1", "str2"], ["str3"]] and hence we dont require to use CombineVectors after getting embeddings from llm.

Comment (eliben) [reply embeddings/embedding.go:110]: The issue is that this functionality exists in langchain-py (see for example `_get_len_safe_embeddings`), and is described here:

https://github.com/openai/openai-cookbook/blob/main/examples/Embedding_long_inputs.ipynb

It's not about splitting a list of texts to batches; it's about taking long texts and splitting them to chunks, since embedding models have limits on text lengths.

Comment (jaylalakiya) [reply embeddings/embedding.go:110]: Absolutely, that makes sense. So there's a conflict between how Python and JS have implemented this.

I implemented batchTexts with an inspiration from how its implemented in JS library [embedDocuments](https://github.com/langchain-ai/langchainjs/blob/4e9e23137de8d2bc61dfbcf05e8e35a8f1e89ef5/langchain/src/embeddings/openai.ts#L154) and [batching function](https://github.com/langchain-ai/langchainjs/blob/f465c286193f5193c89bbafee0290070d459f2ec/langchain-core/src/utils/chunk_array.ts#L1)

By batching we generate maximum number of embeddings possible in single request instead of calling create embeddings separately for each text. This is also good from rate limit point of view because different providers impose different rate limits for eg [OpenAI doc](https://platform.openai.com/docs/guides/rate-limits/free-tier-rate-limits). By batching we can req 2048 texts in single req instead of making 2048 reqs (talking about openai only as it  allows to send upto 2048 texts in single req and each text has context limit of 8191 tokens).

Suggestion: We should do both, batching (batch the texts) and chunking (split the individual text) which will make it most efficient.
Looking forward for your views. I will implement chunking+batching if you agree upon it or I can revert changes made by me which will result in only chunking as it was before.
